export const AUTH_REQUEST_IN_PROGRESS_START = '[AUTH] REQUEST_IN_PROGRESS';
export const AUTH_REQUEST_IN_PROGRESS_END = '[AUTH] AUTH_REQUEST_IN_PROGRESS_END';
export const AUTH_LOGGED_IN = '[AUTH] LOGGED_IN';
export const AUTH_LOGOUT = '[AUTH] LOGOUT';
export const RESET_SIGN_IN = '[AUTH] RESET_SIGN_IN';
