export const SUCCESSFULLY_CONFIRMED_SIGN_UP = '[CONFIRM-SIGN-UP] SUCCESSFULLY_CONFIRMED_SIGN_UP';
export const REQUEST_IN_PROGRESS_CONFIRM_SIGN_UP = '[CONFIRM-SIGN-UP] REQUEST_IN_PROGRESS_CONFIRM_SIGN_UP';
export const REQUEST_IN_PROGRESS_CONFIRMED_SIGN_UP = '[CONFIRM-SIGN-UP] REQUEST_IN_PROGRESS_CONFIRMED_SIGN_UP';
export const SET_CONFIRM_SIGN_UP_ERRORS = '[CONFIRM-SIGN-UP] SET_CONFIRM_SIGN_UP_ERRORS';