export const REQUESTS_IN_PROGRESS_REGISTER = '[SIGN-UP] REQUESTS_IN_PROGRESS_REGISTER';
export const REQUESTS_IN_PROGRESS_REGISTERED = '[SIGN-UP] REQUESTS_IN_PROGRESS_REGISTERED';
export const REGISTERED = '[SIGN-UP] REGISTERED';
export const REGISTRATION_ERROR = '[SIGN-UP] REGISTRATION_ERROR';
export const SET_REGISTRATION_ERRORS = '[SIGN-UP] SET_REGISTRATION_ERRORS';
